### ISSUE TITLE
胖妹子

### ISSUE THREAD

**Issue by wuyongxiu** [wuyongxiu/wuyongxiu.github.io#30]
今天去找笑笑拿书的时候，和笑笑谈到了想做的事情的话题。我感慨北京搞Go开发的工作机会比深圳要多很多，而笑笑说她在滴滴上碰到的10个人中有3个都会是搞外贸的，大概深圳离香港比较近，外贸才是深圳的经济支撑？<br/>
我和笑笑分享了我的一些想法，其中一个就是做自己的大码模特。身为一个比较大只的女生，我买衣服向来不好买，虽然以前有一些譬如一进商店就有没礼貌的店员跟我说“我们家没有你穿的码”这种伤心事，但在这种打击下的我依然没有所谓的减肥成功逆袭，反而是越来越胖（==！！！）。所以无奈之下只有接受这个现实，然而我发现有很多妹子虽然胖但是注重穿搭依然会还挺好看的，并且国外的一些胖妹子仍然可以是很性感美丽的，所以或许虽然胖，但是仍然可以成为胖子里比较好看的，好看的里面比较胖的妹子。<br/>
现在的淘宝上有不少的大码女装店，也有不少的大码模特，微博上也有一些胖妹子穿搭达人，也有一些个人的微信公众号。印象深刻的是有一个APP，顺便运营着一个微信公众号叫做“凹凸曼”，主要就是以胖妹子穿搭为主（这个APP之前的定位某种程度上和我想做的是一样的，涉及到穿搭、妆容、修养，让每一个胖妹子都自信美丽）。凹凸曼里有好几个真的很美丽很会穿搭的胖胖的妹子，她们向我们展示了美女的另一种定义以及告诉每一个胖子们你也可以变得这么美丽。不过APP后来的走向里有一些我不太欣赏的做法（售卖线上减肥营课程，售卖减肥药或者减肥餐），这些纯粹为了利益的行为，一方面利用着用户的信任，出售着可能并没有什么作用或者并不健康的产品，另一方面无时无刻不在告诉着胖妹子们你们不好看，你们不够好，所以你们要拼了命的减肥，吃药、报班。这两点与我心里的为胖妹子设计的产品的理念是不符合的（我的产品的理念是，我想让你改变不是因为你不好，你讨厌自己所以要改变。我想要的是你因为你爱你自己，你爱你的生活，你想要做你自己想做的事情，你想要生活更美好才做改变）。<br/>
相比于app，最常见的还是各大网上商店里的关于胖妹子的服装店铺。自从淘宝利用上了直播的技术之后，有的大码女装店铺也搞起了大码模特现场试穿衣服的直播，我看过一场胖妹子的直播，直播的日点赞人数超过了50万，实时观看人数也达到了好几万，相比于以前只能看着衣服自行脑补到有了卖家秀到大码模特的实时直播以及淘宝推出的模特的小视频，这些技术让胖妹子们能更好的了解服装在自己身上的效果，避免买了不合身衣服的尴尬（胖妹子更容易出现买到不合身衣服的情况，比如上周我在韩都衣舍买了一条裙子，到大腿处居然特么的套不上！！！）<br/>
随着大码店铺逐渐变多，大码模特也渐渐多了起来，看到新闻上说广东比如东莞这些地方就会有相对多的店铺招聘大码模特。不过大码模特的要求也是比较高的，并不是你胖就行了，还要肤白貌美，身高165以上，体重140以上，有腰（除了肤白和有腰，我感觉我都完美符合2333333），所以能够依靠胖挣到钱的还是少数人，大部分胖妹子仍然都是消费者。<br/>
没有肤白，没有有腰，做不了店铺的大码模特，但是我可以做自己的大码模特啊。深圳的各大商场，形形色色的衣服，自己穿搭着玩一玩，搭配的多了好了可以将自己的穿搭通过社交网站发布。不是大码店铺的衣架子，而是胖妹子的服装搭配师。这是一个多么令人激动人心的想法啊~<br/><br/><br/>
PS：我有好多好多想法，好多好多想做的事，但是最重要的是一直没把想法落地==呜呜呜呜呜<br/><br/>
番外：<br/>笑笑说她觉得很多女生都喜欢口红，而且会买很多不同牌子不同色号的口红（笑笑有一大堆哈哈哈哈），但是每支口红都那么大支，很难用完。如果能有一种口红形式，包含很多的口红，而每种口红都只有一小部分，顾客每次都可以根据自己的需求自行DIY口红，这样的话既提高了口红的利用率又丰富了口红的色号，而且还增加了用户的趣味性。在我觉得这是个很有趣的想法的时候，笑笑告诉我说她在淘宝上搜了一下，居然这种形式已经有了相应的概念，叫做“分妆？”（淘宝上的卖家会有各个大牌的口红，然后根据需求合成各种新的类型的口红出售给客户），但是最近分妆因为一些原因（各种口红混合没有经过检验无法保证安全，私自利用各大品牌口红可能涉及侵权），可能无法再在淘宝上卖了。感慨淘宝强大的同时，我们也无法理解，为什么各个品牌没有自己推出这种口红的销售模式呢？为什么每一支口红尺寸都差不多，而没有更小只的了呢？还是因为现有的模式他们能挣得更多？<br/>

**Comment by hunterhug** [comment]
搞事情？
