### ISSUE TITLE
难忘的那些蠢事

### ISSUE THREAD

**Issue by wuyongxiu** [wuyongxiu/wuyongxiu.github.io#36]
我的大部分难忘的经历都是因为穷或蠢......
<br/><br/>

### 第一次睡15元一晚的旅社
2012年7月，高中毕业旅行，和同学一起去黄山旅游，我以为花不了什么钱，一共只带了500块。玩了2天后，大家都走了，只剩下我和王立即要回学校，他只带了1000块。2个人剩余的钱几乎只够买回程的火车票。最后一晚只能睡30元2间房的旅馆，房内只有一张木板床。第二天回去的火车上也是什么都没有吃。
<br/><br/>
### 第一次补不正常的票
2015年，从武汉到南京出火车站的时候我这个小迷糊就找不到我的车票了，当时又有规定，除非补全票，否则不能出火车站。我就在补票口和大叔扭上了，我说我没有那么多钱，大叔脾气又很差，我特么的居然不争气地哭了出来，最后大叔只能让我用20块补了一张80元的票。
<br/><br/>
### 第一次露营
2015年清明节，我和文青去南京看舜天的球赛，第一晚我们俩决定在玄武湖旁边露营。深夜湖边来来往往的有很多不明身份的男人，我们两个人很害怕，最后只能将帐篷偷偷搭在树丛的后面。然而从没有过露营经验的2个人，连睡袋杯子都没带，只能将衣服批在身上。4月份的南京晚上还是比较冷的，当晚又正好是清明节，夜里开始下雨了，一整个夜里，凉气从地上侵入大腿，彻骨的寒气让人腿疼，夜里还能听到猫凄惨的叫声，几乎无法入睡。
<br/><br/>
### 第一次留学
2015年2月，学校有一个去芬兰坦佩雷大学的3+1留学项目，芬兰的学校不用学费，绩点要求也不高，雅思也只要5.5。我和文青看到后，很激动，就在一节课上做了要去留学的决定。然后我们就开始准备成绩，报雅思班学英语。谁知道学院负责这个项目的老师居然向我们每个人征收2万元的费用。开始全面洗脑，整天催文青，要找我们2个谈话，还将我们的offer给扣了，而且往年的几个学姐学长最后都交了钱。但是我们查官方文件都是说了项目不收费的，最后我们2个成功向坦佩雷大学举报了这个老师，得到了坦佩雷大学的支持，我们也都收到了坦佩雷大学的offer。但是最后，由于坦佩雷大学不是名校，本科去读了一年以后仍然要在那里考国外的研究生或者回来就业，这么下来还是要几十万，父母也不是很支持，觉得付出回报不成正比，我也没有信心我会更优秀，我最后还是放弃了我的第一次留学。
<br/><br/>
### 第一次考研
2015年9月，大学最后一年，大家读研出国工作的都基本已经定了下来。然而我保研无望，又不想去找工作，对前途的迷茫，让我只想待在室友身边。
室友们都保研本校，所以我也就决定考研，于是开启了每日泡图书馆的奋斗日子。然而最后，我居然忘记交考研报名费，所以我就果断出来工作了，
因此达成了第一次考研失败的成就。
<br/><br/>
### 第一次表白
2015年11月，当时正是准备考研期间。想想自己因为胆小20多年都没有谈过恋爱，大学生涯即将结束，不免有些遗憾（可见我真的没有好好复习）。燕燕给我出了主意，说要不随便找个人吧，然后就给我指了之前同一个实验室的李卓，我们几个也都在院芭河队里，每天训练都在一起，不过我之前几乎完全没有留意
过他，印象中只有他190的身高，190的体重。然而经室友这么随手一点，我居然真的开始在每次训练的时候关注起了他，莫名其妙觉得他人好像还真的挺不错。于是开始在qq上勾搭他，然而他一直都是友好但是保持着距离。像我这种完全沉不住气的人，感觉被吊了，所以心里很纠结，这种状态仅仅持续一个星期我就受不了了，于是在11月10日当晚，我将他约到了学校的操场上，决定表白了（才勾搭一个星期，简直将感情当儿戏啊...）。恩，我的第一次表白不出意外失败了，但是我却一点儿也不难过==还觉得他是个好人。在操场表白期间，一共有2组人在密切关注这发生的一切，我的室友们跟踪了我，李卓的室友跟踪了李卓。于是当晚几乎整个宿舍楼大四的男生都知道李卓长这么大第一次被表白了==！
<br/><br/>
### 2017年第一个进球
2017年5月，作为为数不多的踢过足球的女生，我终于有机会以主力身份参加一场很重要的女足比赛。在此之前我一直都在魔女队混球，由于刚踢球一年，球技比较差，所以这几个月来只能守门，一直都没进过球。所以这一次，两队几乎都是没踢过球的女生的情况下，作为大腿，我格外珍惜这次机会。场上跑动很积极，脚法也相对不错。一次拿球后，球门10米开外，对方球员贴我很紧，我无法转身，情急之下，一脚抽射，球应声入网，门将已经蒙了。这是我踢球以来进过的最漂亮的一球，然而我是右后卫，进的是我家的大门，蒙的是我家的门将。那场比赛，我们1：2输了比赛。
<br/><br/>
### 其它蠢事

- 在深圳半年实习期间丢了2部手机，并不是被偷走，就是莫名奇妙的找不到了。

- 身份证丢过几次，银行卡丢过几次，公交卡丢过无数次。

- 一个人在上海外滩想要欣赏夜景，然而离开深圳的时候忘记带充电线，一整晚都在找地方买手机充电线，再也没欣赏过夜景。

- 跑马拉松的时候背着的包一路都在掉钥匙，镜子，以及其它莫名奇妙的东西。后面的跑者不停地帮我尖东西。

- 最无意的杀伤力是踩脚，总是会不小心踩到别人的脚，最大的成就是将碧琴的脚指甲踩掉了。

- 工作期间将部门的测试服务器搞挂过2次，并不小心将官网的图片换成了一只树甙熊。

- 减肥最厉害的时候大概是一个月瘦了快15斤，然而第二个月立马反弹了15斤，所以减肥彻底失败，至此再也无法成功。

**Comment by hunterhug** [comment]
好棒

**Comment by salanhess** [comment]
好棒+1！

**Comment by sheldonshen** [comment]
这样的女生,还有么?给我来一打,:smile:
