### ISSUE TITLE
关于博客进度条的体验……

### ISSUE THREAD

**Issue by iampomelo** [wuyongxiu/wuyongxiu.github.io#43]
点开文章的时候，其实已经加载好了，进度条还在动（没看代码，进度条应该是假的），下拉的时候样式还有点问题。
![jietu20180214-162947 2x](https://user-images.githubusercontent.com/12301275/36194470-b8fdc4d0-11a4-11e8-8e3e-ba92b2c4b1df.jpg)

**Comment by iampomelo** [comment]
我在这写还会出现在你博客里啊……那我close了，你知道就好

**Comment by wuyongxiu** [comment]
我还真没关注过这个细节，回头看看==
